### ISSUE TITLE
Command fails with Ruby 2.7.0

### ISSUE THREAD

**Issue by J08nY** [michael-emmi/bam-bam-boogieman#16]
I cloned this repository, then ran `bundle` and `bundle exec bam`. This fails with the error below:

```
>> bundle exec bam
bundler: failed to load command: bam (/usr/lib/ruby/gems/2.7.0/bin/bam)
Traceback (most recent call last):
	22: from /usr/bin/bundle:23:in `<main>'
	21: from /usr/bin/bundle:23:in `load'
	20: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'
	19: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	18: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'
	17: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/cli.rb:24:in `start'
	16: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	15: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/cli.rb:30:in `dispatch'
	14: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	13: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	12: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	11: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/cli.rb:497:in `exec'
	10: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:28:in `run'
	 9: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
	 8: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `load'
	 7: from /usr/lib/ruby/gems/2.7.0/bin/bam:23:in `<top (required)>'
	 6: from /usr/lib/ruby/gems/2.7.0/bin/bam:23:in `load'
	 5: from /home/.../dev/bam-bam-boogieman/exe/bam:4:in `<top (required)>'
	 4: from /home/.../dev/bam-bam-boogieman/exe/bam:4:in `require'
	 3: from /home/.../dev/bam-bam-boogieman/lib/bam.rb:9:in `<top (required)>'
	 2: from /home/.../dev/bam-bam-boogieman/lib/bam.rb:9:in `require_relative'
	 1: from /home/.../dev/bam-bam-boogieman/lib/bpl/parser.tab.rb:12:in `<top (required)>'
/home/.../dev/bam-bam-boogieman/lib/bpl/parser.tab.rb:12:in `require_relative': /home/.../dev/bam-bam-boogieman/lib/bpl/ast/program.rb:20: circular argument reference - prefix (SyntaxError)
```

The versions of Ruby and Bundler are as below.

```
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
Bundler version 2.2.3
```

**Comment by J08nY** [comment]
Just tested that Ruby 2.5.5  (`ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]`) works.

**Comment by michael-emmi** [comment]
Hi @J08nY, we’d be happy to merge a pull request for the fix.
