### ISSUE TITLE
add_assertion is undefined in security/shadowing

### ISSUE THREAD

**Issue by J08nY** [michael-emmi/bam-bam-boogieman#17]
When running Bam with ct-verif (`test-automation` branch) the following error happens (on the `sort` example).

```
Traceback (most recent call last):
	47: from /home/.../.rvm/gems/ruby-2.5.5/bin/bam:23:in `<main>'
	46: from /home/.../.rvm/gems/ruby-2.5.5/bin/bam:23:in `load'
	45: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/exe/bam:6:in `<top (required)>'
	44: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bam.rb:154:in `main'
	43: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bam/prelude.rb:140:in `timed'
	42: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bam.rb:156:in `block in main'
	41: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bam.rb:156:in `each'
	40: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bam.rb:156:in `block (2 levels) in main'
	39: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/shadowing.rb:616:in `run!'
	38: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:126:in `each_child'
	37: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:126:in `each'
	36: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:126:in `each'
	35: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:124:in `block in each_child'
	34: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:174:in `enumerate_children'
	33: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:174:in `each'
	32: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:179:in `block in enumerate_children'
	31: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:179:in `each'
	30: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:179:in `block (2 levels) in enumerate_children'
	29: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:179:in `yield'
	28: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/shadowing.rb:623:in `block in run!'
	27: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/shadowing.rb:592:in `selective_self_composition'
	26: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/shadowing.rb:365:in `add_assertions!'
	25: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:117:in `each'
	24: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:117:in `each'
	23: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:117:in `each'
	22: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:115:in `block in each'
	21: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:162:in `enumerate'
	20: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:162:in `each'
	19: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:167:in `block in enumerate'
	18: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:167:in `each'
	17: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:167:in `block (2 levels) in enumerate'
	16: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:162:in `enumerate'
	15: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:162:in `each'
	14: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:167:in `block in enumerate'
	13: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:167:in `each'
	12: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:167:in `block (2 levels) in enumerate'
	11: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:161:in `enumerate'
	10: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:161:in `yield'
	 9: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/shadowing.rb:367:in `block in add_assertions!'
	 8: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/shadowing.rb:367:in `each'
	 7: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/shadowing.rb:368:in `block (2 levels) in add_assertions!'
	 6: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/shadowing.rb:368:in `each'
	 5: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/shadowing.rb:368:in `each'
	 4: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/shadowing.rb:120:in `block in loads'
	 3: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/shadowing.rb:120:in `times'
	 2: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/shadowing.rb:121:in `block (2 levels) in loads'
	 1: from /home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/shadowing.rb:121:in `yield'
/home/.../.rvm/gems/ruby-2.5.5/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/shadowing.rb:369:in `block (3 levels) in add_assertions!': undefined method `add_assertion' for #<Bpl::Shadowing:0x00005649314c8a80> (NoMethodError)
Did you mean?  add_assertion!
               add_assertions!

failed to construct product program
```

The issue seems to be in https://github.com/michael-emmi/bam-bam-boogieman/blob/master/lib/bpl/passes/security/shadowing.rb#L369. Which should likely be `add_assertion!` instead of `add_assertion`. Tested with `Ruby 2.5.5` (SMACK 2.3.6).

**Comment by J08nY** [comment]
Just tested that changing the `add_assertion` over to `add_assertion!` fixes this issue.

**Comment by michael-emmi** [comment]
Hi @J08nY, we’d be happy to merge a pull request for the fix.
